# APC 523 HW1 Problem 7

In [15]:
import numpy as np
import matplotlib.pyplot as plt

import math

## Define the polynomial

Wilkinson's polynomial:
$$ w(x) = \prod_{k=1}^{20} (x-k) = (x-1)(x-2) \cdots (x-20)$$

We can expand out the factors recursively.

In [98]:
def wilkinson_polynomial_coeffs(n=20):
    '''
    Get polynomial coefficients recursively.
    '''
    # Base case
    if n == 1:
        return np.asarray([-1, 1], dtype='object')
    
    # Recurse
    prev = wilkinson_polynomial_coeffs(n-1)
    coeffs = np.empty(n+1, dtype='object')
    coeffs[n] = 1
    for i in range(1, n):
        coeffs[i] = prev[i-1] - n * prev[i]
    coeffs[0] = -n * prev[0]
    
    return coeffs


In [99]:
wp_int = wilkinson_polynomial_coeffs(20)

In [100]:
wp_int[::-1]

array([1, -210, 20615, -1256850, 53327946, -1672280820, 40171771630,
       -756111184500, 11310276995381, -135585182899530, 1307535010540395,
       -10142299865511450, 63030812099294896, -311333643161390640,
       1206647803780373360, -3599979517947607200, 8037811822645051776,
       -12870931245150988800, 13803759753640704000, -8752948036761600000,
       2432902008176640000], dtype=object)

In [172]:
ps = ''
for i in range(len(wp_int)-1, -1, -1):
    sgn = np.sign(wp_int[i])
    ps += (' + ' if sgn == 1 else ' - ')
    ps += '{0:d}x^{{{1:d}}}'.format(abs(wp_int[i]), i)
ps

' + 1x^{20} - 210x^{19} + 20615x^{18} - 1256850x^{17} + 53327946x^{16} - 1672280820x^{15} + 40171771630x^{14} - 756111184500x^{13} + 11310276995381x^{12} - 135585182899530x^{11} + 1307535010540395x^{10} - 10142299865511450x^{9} + 63030812099294896x^{8} - 311333643161390640x^{7} + 1206647803780373360x^{6} - 3599979517947607200x^{5} + 8037811822645051776x^{4} - 12870931245150988800x^{3} + 13803759753640704000x^{2} - 8752948036761600000x^{1} + 2432902008176640000x^{0}'

In [173]:
wp = np.asarray(wp_int, dtype=np.float64)

In [174]:
wpoly = np.polynomial.Polynomial(wp)

## Compute roots using built-in methods

In [107]:
import scipy.optimize

In [180]:
nr_root = scipy.optimize.newton(wpoly, 21)
print(nr_root, (nr_root - 20.0)/20.0)

19.9999949571418 -2.5214290992892075e-07


In [181]:
np_root = wpoly.roots()[-1]
print(np_root, (np_root - 20.0)/20.0)

(20.000542093702702+0j) (2.7104685135093123e-05+0j)


In [184]:
for perturb in [1e-8, 1e-6, 1e-4, 1e-2]:
    wp_perturb = np.copy(wp)
    wp_perturb[-1] += perturb
    poly_perturb = np.polynomial.Polynomial(wp_perturb)
    perturbed_root = scipy.optimize.newton(poly_perturb, 21, maxiter=100)
    
    print('Perturbation = {0:.1e}, root = {1:.10g}, rel. error = {2:.3g}'.format(perturb,
                perturbed_root, (perturbed_root - 20)/20))

Perturbation = 1.0e-08, root = 9.585389647, rel. error = -0.521
Perturbation = 1.0e-06, root = 7.752713003, rel. error = -0.612
Perturbation = 1.0e-04, root = 5.96933485, rel. error = -0.702
Perturbation = 1.0e-02, root = 5.469592915, rel. error = -0.727


In [182]:
wp_perturb = np.copy(wp)
wp_perturb[-1] += 1.0e-6
poly_perturb = np.polynomial.Polynomial(wp_perturb)
poly_perturb.roots()

array([ 1.        +0.j        ,  2.        +0.j        ,
        3.        +0.j        ,  3.99999987+0.j        ,
        5.00000508+0.j        ,  5.99962991+0.j        ,
        7.01924407+0.j        ,  7.75224496+0.j        ,
        8.6417218 -1.00752734j,  8.6417218 +1.00752734j,
        9.99509845-2.28807145j,  9.99509845+2.28807145j,
       11.8655255 -3.74753662j, 11.8655255 +3.74753662j,
       14.65897489-5.1502364j , 14.65897489+5.1502364j ,
       18.8039955 -5.53148348j, 18.8039955 +5.53148348j,
       23.1490169 -2.7409845j , 23.1490169 +2.7409845j ])

In [185]:
wp_perturb = np.copy(wp)
wp_perturb[-2] -= 2**-23
poly_perturb = np.polynomial.Polynomial(wp_perturb)

In [186]:
scipy.optimize.newton(poly_perturb, 21, maxiter=100)

20.846907731075376

In [192]:
scipy.optimize.newton(poly_perturb, 17, maxiter=100)

8.00730481681552

In [193]:
poly_perturb.roots()

array([ 1.        +0.j        ,  2.        +0.j        ,
        3.        +0.j        ,  4.00000002+0.j        ,
        4.99999985+0.j        ,  6.00000831+0.j        ,
        6.99965899+0.j        ,  8.00777435+0.j        ,
        8.9146078 +0.j        , 10.09442898-0.64843958j,
       10.09442898+0.64843958j, 11.79460279-1.65426469j,
       11.79460279+1.65426469j, 13.99301797-2.51922164j,
       13.99301797+2.51922164j, 16.73096403-2.81265595j,
       16.73096403+2.81265595j, 19.50249798-1.94032951j,
       19.50249798+1.94032951j, 20.8469273 +0.j        ])

## Condition numbers

In [198]:
wprime_int = np.zeros(len(wp_int)-1, dtype='object')
for i in range(0, len(wprime_int)):
        wprime_int[i] = (i+1) * wp_int[i+1]

In [200]:
wprime = np.polynomial.Polynomial(wprime_int)

In [212]:
for r in [14, 16, 17, 20]:
    cond_num = 0.0
    for i in range(20):
        cond_num += np.abs(wp_int[i] * (r**(i-1)) / wprime(r))
#     indices = np.arange(20, dtype='object') - 1
#     cond_num = np.sum(np.abs(wp_int[:-1] * (r**indices) / wprime(r)))
    print('cond({0:d}) = {1:.8g}'.format(r, cond_num))

cond(14) = 5.3977328e+13
cond(16) = 3.5431949e+13
cond(17) = 1.8121772e+13
cond(20) = 1.3780364e+11


In [205]:
wp_int[:-1]

array([2432902008176640000, -8752948036761600000, 13803759753640704000,
       -12870931245150988800, 8037811822645051776, -3599979517947607200,
       1206647803780373360, -311333643161390640, 63030812099294896,
       -10142299865511450, 1307535010540395, -135585182899530,
       11310276995381, -756111184500, 40171771630, -1672280820, 53327946,
       -1256850, 20615, -210], dtype=object)

In [209]:
np.arange(20, dtype='object')

array([1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192,
       16384, 32768, 65536, 131072, 262144, 524288], dtype=object)